server:
  port: 8010
spring:
  application:
    name: home-
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  servlet:
    multipart:
      fileSizeThreshold: 300MB
      enabled: true
      maxFileSize: 300MB
      maxRequestSize: 300MB
springdoc:
  swaggerUi:
    path: docs